"""add_fixability_type_and_reason

Revision ID: 373c38625ac4
Revises: 655ae8848052
Create Date: 2026-07-30 18:49:50.068375
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers
revision: str = '373c38625ac4'
down_revision: Union[str, None] = '655ae8848052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixability_flags', sa.Column('fixability_type', sa.Text(), server_default=sa.text("'too_vague'"), nullable=False))
    op.add_column('fixability_flags', sa.Column('fixability_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixability_flags', 'fixability_reason')
    op.drop_column('fixability_flags', 'fixability_type')
    # ### end Alembic commands ###
