"""Add fit_tier and bridge_note to Card

Revision ID: 655ae8848052
Revises: e4b533252466
Create Date: 2026-07-30 17:39:17.684605
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers
revision: str = '655ae8848052'
down_revision: Union[str, None] = 'e4b533252466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('fit_tier', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('bridge_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'bridge_note')
    op.drop_column('cards', 'fit_tier')
    # ### end Alembic commands ###
