"""Add LLM fields to Card

Revision ID: e4b533252466
Revises: eef6fe76374f
Create Date: 2026-07-30 14:30:26.005286
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'e4b533252466'
down_revision: Union[str, None] = 'eef6fe76374f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('gap_description', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('matching_reasoning', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('source_urls', postgresql.ARRAY(sa.Text()), nullable=True))
    op.drop_index('ix_cards_company_id', table_name='cards')
    op.drop_index('ix_cards_profile_match_score', table_name='cards')
    op.drop_index('ix_cards_status', table_name='cards')
    op.drop_index('ix_cards_user_id', table_name='cards')
    op.drop_index('ix_contacts_company_id', table_name='contacts')
    op.drop_index('ix_contacts_contact_type', table_name='contacts')
    op.drop_index('ix_gap_clusters_company_id', table_name='gap_clusters')
    op.drop_index('ix_gap_clusters_rank_score', table_name='gap_clusters')
    op.drop_index('ix_outreach_drafts_card_id', table_name='outreach_drafts')
    op.drop_index('ix_outreach_drafts_user_id', table_name='outreach_drafts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outreach_drafts_user_id', 'outreach_drafts', ['user_id'], unique=False)
    op.create_index('ix_outreach_drafts_card_id', 'outreach_drafts', ['card_id'], unique=False)
    op.create_index('ix_gap_clusters_rank_score', 'gap_clusters', ['rank_score'], unique=False)
    op.create_index('ix_gap_clusters_company_id', 'gap_clusters', ['company_id'], unique=False)
    op.create_index('ix_contacts_contact_type', 'contacts', ['contact_type'], unique=False)
    op.create_index('ix_contacts_company_id', 'contacts', ['company_id'], unique=False)
    op.create_index('ix_cards_user_id', 'cards', ['user_id'], unique=False)
    op.create_index('ix_cards_status', 'cards', ['status'], unique=False)
    op.create_index('ix_cards_profile_match_score', 'cards', ['profile_match_score'], unique=False)
    op.create_index('ix_cards_company_id', 'cards', ['company_id'], unique=False)
    op.drop_column('cards', 'source_urls')
    op.drop_column('cards', 'matching_reasoning')
    op.drop_column('cards', 'gap_description')
    # ### end Alembic commands ###
