"""Add file_hash and parse_status to user_profiles

Revision ID: eef6fe76374f
Revises: 0007
Create Date: 2026-07-30 11:12:34.544486
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers
revision: str = 'eef6fe76374f'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('file_hash', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('parse_status', sa.Text(), nullable=False, server_default='SUCCESS'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'parse_status')
    op.drop_column('user_profiles', 'file_hash')
    # ### end Alembic commands ###
